### ISSUE TITLE
Unit test fail when switching network

### ISSUE THREAD

**Issue by skyttedk** [protocol/nft-website#121] opened 2021-07-14 22:23 UTC
It seems that when changing from HardHat network to another network(in my case ganache) unit tests fail with message;

"Signature invalid or unauthorized"

The error is thrown when redeeming a voucher, and further investigation shows that it is the _verify function that 
returns a wrong signer address:

        address signer = _verify(voucher);

my setup is 

```
module.exports = {
    solidity: "0.8.0",
    defaultNetwork: "ganache",
    networks: {
        hardhat: {},
        ganache: {
            url: "HTTP://127.0.0.1:7545",
            accounts: ["ddbcf049f81dc07d8f02f18aa2b4e8065240eb4ce030f4458fb0185277381819",
                "45aca4baa5b5140497203dee2fce43912dd5ddd02767bef9e3def1a8518145ad",
                "a079faf901038511647235487cb2b261f8ef2f0f86b1d97198b1bd0fec1e4261",
                "2e2ff3db164ff96b502124d91edc603faa989a698347e03391eba3eb43815adc",
                "7123c5f0842c4b67d0269f919f908a43a2a5cac640a156bd43cc4281077fc4f6",
                "7cc2ee754c33703c65d90acb794deaa4d9b6a825a3d7175ea768470cdd42f2f9",
                "a986fc539674e2fa5e91095e41eca8c6d818502fe506e5bdb94c20767150be40",
                "b52df78b66a82ccd93b1fc200dcfbd1a5615672ece122bff795300e56613c4fd",
                "786574bc4b53f1cdc8b1eadba08af1b012cc14e4ea12f0d7306371bc0e10f0e1",
                "fea73b4aef8ba751433e1fe0c079db0e033cff607b411d226abeb383835cbbd6"
            ]
        }
    }
};
```

**Comment by jessicaschilling** [comment] 2021-07-14 22:30
@yusefnapora or @johndmulhausen -- can you please have a look?

**Comment by yusefnapora** [comment] 2021-07-20 14:04
Interesting, thanks for the report. The signing domain includes the chain id of the network, so maybe the signatures are being prepared for the hardhat network instead of ganache. I'll try using ganache to reproduce.

**Comment by yusefnapora** [comment] 2021-07-20 21:43
This is a strange one... I can't get it to work with the ganache GUI, but it works with `ganache-cli` _if_ you use `ganache-cli --chainId=<something>` and set the same `chainId` in your hardhat config. What's weird is that it works if you explicitly set the chain id to the default (1337) when running `ganache-cli`, but it doesn't work if you just leave it as the default and don't set the `--chainId` flag. Not sure what's going on there...

**Comment by yusefnapora** [comment] 2021-07-21 16:27
@skyttedk I think I've figured out the cause of this issue. According to the [ganache-cli docs](https://github.com/trufflesuite/ganache-cli), the default behavior is to return `1337` from the `eth_chainId` RPC method, but `1` from the on-chain `CHAINID` opcode.

> --chainId: Specify the Chain ID ganache-cli will use for eth_chainId RPC and the CHAINID opcode. For legacy reasons, the default is currently 1337 for eth_chainId RPC and 1 for the CHAINID opcode. Setting this flag will align the chainId values. This will be fixed in the next major version of ganache-cli and ganache-core!

The signatures get created using the chain id returned by the RPC method, but then they're getting validated using the chain id returned by the `CHAINID` opcode on-chain. Setting the `--chain-id` flag sets both values, which is why it works if you set the flag but doesn't work if you leave the defaults alone.

I guess as a workaround, I could include a contract function that returns the on-chain value of `CHAINID` and use it to generate the signatures, instead of relying on the `eth_chainId` rpc call. I'll make a new issue for that and close this one. 

It may take a little while before I'll have time to implement the workaround. In the meantime, you should be able to run with `ganache-cli --chain-id=1337`.

**Closed by yusefnapora** 2021-07-21 16:27 UTC
Labels: need/triage

**Comment by yusefnapora** [comment] 2021-07-21 19:45
@skyttedk I ended up grabbing this today after all and merged in the workaround to the examples repo. Feel free to reopen this issue if the fix didn't work for you.

**Comment by skyttedk** [comment] 2021-07-24 07:49
@yusefnapora It works like a charm :)Thanks for a fast response to this issue.
